assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: false
  test: false
instrument: CE01ISSP-SP001-06-NUTNRJ000
stream:
  method: telemetered
  name: nutnr_j_cspp_instrument
workflow_config:
  schedule: 0 0 * * *
